[package]
name = "vedit-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
vedit-config = { path = "../vedit-config" }
